### ISSUE TITLE
Include mechanic similar to "XrpcAuthPlugin" in bluesky library

### ISSUE THREAD

**Issue by CanYumusak** [christiandeange/ozone#11]
Thank you for working on this library! This was exactly what I was searching for.

Playing around with the library a little I really missed a class similar to `XrcpAuthPlugin` in the main library. Most devs will probably copy the plugin or rewrite a quite similar one.

Thanks!

**Comment by christiandeange** [comment]
Good idea, been thinking about this too. Does the current interface for configuring `XrcpAuthPlugin ` make sense for your use case, or are there any other kinds of changes you'd like to see in there as well?

**Comment by CanYumusak** [comment]
To be honest it felt counterintuitive to add the token handling to the HTTP client when using a library. I was expecting to implement a "more automatic" way of token handling and pass it to the constructor of `XrpcBlueskyApi`.

Also I am using this in a scenario where I do not care much about persisting the RT.  The API is a bit weird in this case (I have to save the tokens in a Flow which is then passed to the plugin). 

Generally (in my use-case) I would've wished for a more "pass handle & password into the API and be done" kind of approach, although I do understand that there might be use-cases where folks want a finer management of tokens.

**Comment by christiandeange** [comment]
Good point there. Sounds like it might be preferable to instead have a different implementation of the `BlueskyApi` that mostly delegates to `XrpcBlueskyApi`, but also manages all the authentication bits like auth + refresh tokens for you so that it's completely transparent.
