### ISSUE TITLE
Query params for GetAuthorFeed filter uses the wrong casing

### ISSUE THREAD

**Issue by tunjid** [christiandeange/ozone#15]
Logs of the get author feed request show it's being sent as the following:

```
https://bsky.social/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3A6q4y7p2wft3tncsffspts3m5&limit=50&filter=PostsWithMedia&includePins=false
```

It should be

```
https://bsky.social/xrpc/app.bsky.feed.getAuthorFeed?actor=did%3Aplc%3A6q4y7p2wft3tncsffspts3m5&filter=posts_with_media&includePins=false
```

It seems its because the parameters are parse as `Any?.toString` instead of using the enum value:

```
public fun HttpRequestBuilder.parameter(key: String, value: Any?): Unit =
    value?.let { url.parameters.append(key, it.toString()) } ?: Unit
```

This is most likely because the sealed class `GetAuthorFeedFilter` sealed class uses data objects that override the `toString` of `AtpEnum`.

**Comment by christiandeange** [comment]
> This is most likely because the sealed class `GetAuthorFeedFilter` sealed class uses data objects that override the `toString` of `AtpEnum`.

Seems like it's exactly this – `data object`s use the autogenerated toString which override the explicitly defined in `AtpEnum`. Thankfully the fix is rather simple.
